### ISSUE TITLE
License error

### ISSUE THREAD

**Issue by DaRkProaso** [SwareJonge/IEStrikers#3]
I think I'm an idiot but I don't know why I am getting license errors, I think I put them correctly but it seems that's not the case
![image](https://github.com/SwareJonge/IEStrikers/assets/122731819/ce710609-3809-407d-ade1-aa585226d884)
![image](https://github.com/SwareJonge/IEStrikers/assets/122731819/75a1d2d8-23bb-4519-8260-0e2abc98f214)

**Comment by SwareJonge** [comment]
It could be that the DLLs inside that folder aren't cracked(somehow)  I'd try the ones from 1.7
Or get it all from [here](https://files.decomp.dev/compilers_latest.zip)

**Comment by DaRkProaso** [comment]
That worked, but now [this](https://github.com/user-attachments/files/15823182/error.txt) happens

**Comment by SwareJonge** [comment]
Hmm that probably I means I messed up somewhere, I'll need to do some further investigation

**Comment by SwareJonge** [comment]
Turns out i've tried to link a file that wasn't matching. Thanks for catching this, it should work all fine now
